openclassdut_accueil:
    path: /
    controller: App\Controller\OpenclassdutController::index

openclassdut_entreprises:
    path: /entreprises
    controller: App\Controller\OpenclassdutController::entreprises

openclassdut_formations:
    path: /formations
    controller: App\Controller\OpenclassdutController::formations

openclassdut_stages:
    path: /stages/{id}
    controller: App\Controller\OpenclassdutController::stages
    
openclassdut_stagesListe:
    path: /stagesListe
    controller: App\Controller\OpenclassdutController::stagesListe

openclassdut_stagesEntreprise:
    path: /stagesFiltres/entreprise/{id}
    controller: App\Controller\OpenclassdutController::stagesEntreprise

openclassdut_stagesFormation:
    path: /stagesFiltres/formation/{id}
    controller: App\Controller\OpenclassdutController::stagesFormation