prostages_accueil:
    path: /
    controller: App\Controller\prostagesController::index

prostages_entreprises:
    path: /entreprises
    controller: App\Controller\prostagesController::entreprises

prostages_formations:
    path: /formations
    controller: App\Controller\prostagesController::formations

prostages_stages:
    path: /stages/{id}
    controller: App\Controller\prostagesController::stages
    
prostages_stagesListe:
    path: /stagesListe
    controller: App\Controller\prostagesController::stagesListe

prostages_stagesEntreprise:
    path: /stagesFiltres/entreprise/{id}
    controller: App\Controller\prostagesController::stagesEntreprise

prostages_stagesFormation:
    path: /stagesFiltres/formation/{id}
    controller: App\Controller\prostagesController::stagesFormation

tps_s4_parEntreprise:
    path: /parEntreprise/{id}
    controller: App\Controller\prostagesController::parEntreprise

tps_s4_parFormation:
    path: /parFormation/{nom}
    controller: App\Controller\prostagesController::parFormation    